name: Build OpenWrt Docker x86-64 image

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  FIRMWARE_URL: "https://github.com/haiibo/OpenWrt/releases/download/X86_64/openwrt-x86-64-generic-rootfs.tar.gz"
  REPOSITORY: crazygit/openwrt-x86-64
  TAG: latest

jobs:
  build:
    name: "Build OpenWrt docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Download Firmware
        run: |
          wget $FIRMWARE_URL -O openwrt.tar.gz

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          FIRMWARE: openwrt.tar.gz 
        with:
          name: ${{ env.REPOSITORY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          buildargs: FIRMWARE
          tags: "latest,${{ env.TAG }}"
      - name: Organize files  
        id: organize
        if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
        run: |
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          echo "::set-output name=status::success"
      - name: Upload firmware directory
        uses: actions/upload-artifact@main
        if: steps.organize.outputs.status == 'success' && !cancelled()
        with:
         name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
         path: ${{ env.FIRMWARE }}
